---
- name: Verify
  hosts: all
  tasks:
  
  - name: Check powershell version
    command: "powershell -Version"
    ignore_errors: yes
    register: powershell_current_version

  - name: Ensure powershell is not installed
    assert:
      that:
        - powershell_current_version.rc != 0