---
#--------------------------------------------------------------
# Debug
#--------------------------------------------------------------
# - name: Get {{ ansible_os_family }}
#   debug:
#     msg: "{{ ansible_os_family }}"

# - name: Get powershell_json_response
#   debug:
#     msg: "{{ powershell_json_response }}"

#--------------------------------------------------------------
# Tasks
#--------------------------------------------------------------
- name: Include tasks for install
  include_tasks: "install.yml"
  when: >
    uninstall == false
  tags:
    - install

- name: Include tasks for uninstall
  include_tasks: "uninstall.yml"
  when: >
    uninstall == true
  tags:
    - uninstall